Id 10
A1zYu/HomeForPets pull request #27
Opened 2024-09-13 22:54 UTC by A1zYu

2024-09-19 22:29 UTC, A1zYu commented
[get all volunteerDto + dapper + refactoring] активный коммит

2024-09-20 08:57 UTC, KirillSachkov requested changes

2024-09-20 08:57 UTC, KirillSachkov commented on backend/src/HomeForPets.Application/Dtos/VolunteerDto.cs
> +public class VolunteerDto
Вынеси все классы по своим файлам

2024-09-20 08:57 UTC, KirillSachkov commented on backend/src/HomeForPets.Infrastructure/Configurations/Write/VolunteerConfiguration.cs
> +            ).HasColumnName("social_networks");
Я бы вынес это в extension методы, так как в будущем таких конфигураций может появиться больше

2024-09-20 08:57 UTC, KirillSachkov commented on backend/src/HomeForPets.Infrastructure/Repositories/VolunteersRepository.cs
> +        _dbConnection = dbContext.Database.GetDbConnection();
Зачем тебе это?

2024-09-20 08:57 UTC, KirillSachkov commented on backend/src/HomeForPets.Infrastructure/SqlConnectionFactory.cs
> +    new NpgsqlConnection(_configuration.GetConnectionString("localDb"));
вынеси localdb в константу

2024-09-25 14:38 UTC, merged