ID-B-13
A1zYu/HomeForPets pull request #31
Opened 2024-09-27 15:08 UTC by A1zYu

2024-09-29 07:41 UTC, KirillSachkov requested changes

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Api/Controllers/Volunteers/VolunteerController.cs
> +    public async Task<IActionResult> UpdateMainInfoForPet(
Здесь мы обновляем всю информацию, поэтому лучше назвать UpdatePet

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Application/VolunteersManagement/Commands/DeleteFileFromPet/DeleteFileFromPetHandler.cs
> +public class DeleteFileFromPetHandler : ICommandHandler<bool, DeleteFileFromPetCommand>
DeletePhoto

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Api/Controllers/Volunteers/VolunteerController.cs
> +    public async Task<IActionResult> DeleteFilePet(
DeletePhoto

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Application/VolunteersManagement/Commands/DeleteFileFromPet/DeleteFileFromPetHandler.cs
> +            await _fileProvider.DeleteFile(new FileInfo(FilePath.Create(photo.Path).Value, BUCKET_NAME),ct);
А если не получится удалить файл, что тогда? нужно чтобы этот метод возвращал результат и дальше была проверка

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Application/VolunteersManagement/Commands/DeleteFileFromPet/DeleteFileFromPetHandler.cs
> +            var result = volunteer.Value.DeletePhotoToPet(command.PetId, command.PhotoId);
Лучше назвать DeletePetPhoto

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/VolunteersManagement/Entities/Pet.cs
> +    public UnitResult<Error> UpdateInfo(Pet updatedPet)
можно не возвращать результат, просто void

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/VolunteersManagement/Entities/Pet.cs
> +    public UnitResult<Error> UpdateInfo(Pet updatedPet)
этот метод должен иметь internal модификатор доступа

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/VolunteersManagement/Entities/Pet.cs
> +    public UnitResult<Error> DeletePhoto(PetPhotoId petPhotoId)
internal

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/VolunteersManagement/Entities/Pet.cs
> +    public UnitResult<Error> UpdateInfo(Pet updatedPet)
чтобы извне нельзя было вызвать этот метод, только волонтер может это делать

2024-09-29 07:41 UTC, KirillSachkov commented on backend/src/HomeForPets.Infrastructure/Repositories/SpeciesRepository.cs
> +    public async Task<UnitResult<Error>> DeleteBreed(SpeciesId speciesId,BreedId breedId, CancellationToken ct)
Репозиторий не должен заниматься бизнес логикой, это удаление нужно делать через агрегат вида, а потом просто сохранять данные

2024-09-30 08:05 UTC, YADARAN1 approved these changes

2024-09-30 08:21 UTC, KirillSachkov requested changes

2024-09-30 08:21 UTC, KirillSachkov commented on backend/src/HomeForPets.Infrastructure/Repositories/SpeciesRepository.cs
>  }
Такого метода в репозитории быть не должно, потому что это по сути бизнес логика. Удаление породы нужно делать через агрегат Species. То есть ты внутри модели делаешь метод по удалению породы, там ищешь нужную породу, удаляешь её из списка и потом сохраняешь просто изменения в базе данных. И это всё естественно должно быть в сервисе, а не в репозитории. Не забыть сделать проверку на то, что нет животных, которые используют эту породу

2024-09-30 09:33 UTC, KirillSachkov approved these changes

2024-09-30 09:39 UTC, merged