ID-B-4.1
A1zYu/HomeForPets pull request #5
Opened 2024-08-13 10:47 UTC by A1zYu

https://windy-reward-6f6.notion.site/PetFamily-0a8277b67f8b4cf59d979de6e9756bce?p=dbe7fe76c38f4dccb5cd4f4f23a9a6ae&pm=c

2024-08-13 10:49 UTC, KirillSachkov requested changes
Задание выполнено не полностью, нет конфигураций, миграций, логирования, использования snake_case

2024-08-13 10:51 UTC, A1zYu commented
@KirillSachkov  я выполнил 1 пункт этой задачи. После проверки думал выполнить след пункт

2024-08-13 11:00 UTC, KirillSachkov commented
> @KirillSachkov я выполнил 1 пункт этой задачи. После проверки думал выполнить след пункт

Лучше выполнить всё сразу, так будет удобнее проверять

2024-08-13 16:32 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Pet.cs
> +    private List<PetPhoto> _petPhotos = [];
Забыл добавить readonly

2024-08-13 16:33 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Pet.cs
> +    private Pet(Guid id, string name, string species, string description, string breed, string color, string healthInfo,
EF Core автоматически создаёт Id для новой сущности, делать это необязательно, можешь убрать, можешь оставить

2024-08-13 16:33 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Pet.cs
> +        Id = id;
EF Core автоматически создаёт Id для новой сущности, делать это необязательно, можешь убрать, можешь оставить

2024-08-13 16:34 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Pet.cs
> +    public static Result<Pet> Create(Guid id, string name, string species, string description, string breed,
EF Core автоматически создаёт Id для новой сущности, делать это необязательно, можешь убрать, можешь оставить

2024-08-13 16:35 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Pet.cs
> +            Id = Guid.NewGuid(),
EF Core автоматически создаёт Id для новой сущности, делать это необязательно, можешь убрать, можешь оставить

2024-08-13 16:38 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Volunteer.cs
> +    public Result<Volunteer> Create(string fullName)
Забыл добавить static

2024-08-13 16:39 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Volunteer.cs
> +        if (string.IsNullOrWhiteSpace(fullName))
Из свойства FullName лучше сделать ValueObject и добавить туда 3 свойства ФИО

2024-08-13 16:47 UTC, YADARAN1 commented on backend/src/HomeForPets.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.Property(p => p.Name).IsRequired().HasMaxLength(Constraints.LOW_VALUE_LENGTH);
Это не ошибка, больше по стилю кода, лучше всегда писать так

builder.Property(p => p.Name)
.IsRequired()
.HasMaxLength(Constraints.LOW_VALUE_LENGTH);

Так читается проще и лучше, но можешь оставить как есть

2024-08-13 18:45 UTC, YADARAN1 requested changes

2024-08-13 18:45 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/Models/Volunteer.cs
> +    public Result<Volunteer> Create(string firstName,string lastName, string middleName)
Класс должен быть статическим

2024-08-13 18:45 UTC, YADARAN1 commented on backend/src/HomeForPets.Domain/ValueObject/FullName.cs
> +    public string LastName { get; private set; } = default!;
У ValueObject'ов не может быть private set;

2024-08-14 07:01 UTC, KirillSachkov requested changes

2024-08-14 07:01 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/ValueObject/FullName.cs
> +    public string MiddleName { get;  } = default!;
Отчество нужно сделать необязательным

2024-08-14 07:01 UTC, KirillSachkov commented on backend/src/HomeForPets.Infrastructure/ApplicationDbContext.cs
> +    public DbSet<Pet> Pets => Set<Pet>();
Здесь нужен только один DbSet - Volunteer

2024-08-14 10:03 UTC, KirillSachkov approved these changes

2024-08-14 10:03 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/Models/PaymentDetails.cs
> +    public Guid? PetId { get; private set; }
Эти id здесь не нужны

2024-08-14 10:03 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/ValueObject/Address.cs
> +public class Address
должен быть record

2024-08-14 10:03 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/ValueObject/FullName.cs
> +    private FullName(){}
Этот конструктор здесь не нужен

2024-08-14 10:03 UTC, KirillSachkov commented on backend/src/HomeForPets.Domain/ValueObject/Address.cs
> +    private Address()
Этот конструктор здесь не нужен, так как это не сущность

2024-08-14 10:04 UTC, KirillSachkov requested changes
Комментарии указал выше

2024-08-14 10:31 UTC, KirillSachkov approved these changes

2024-08-14 10:32 UTC, merged